/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AccountDetailModal: typeof import('./../components/AccountDetailModal.vue')['default']
    Button: typeof import('./../components/base/Button.vue')['default']
    CreateIdentityModal: typeof import('./../components/CreateIdentityModal.vue')['default']
    CreatePolicyModal: typeof import('./../components/CreatePolicyModal.vue')['default']
    IdentityDetailModal: typeof import('./../components/IdentityDetailModal.vue')['default']
    LinkAccountModal: typeof import('./../components/LinkAccountModal.vue')['default']
    PolicyDetailModal: typeof import('./../components/PolicyDetailModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
